### ISSUE TITLE
Cannot find uORF file

### ISSUE THREAD

**Issue by mvelinder** [ImperialCardioGenetics/UTRannotator#2]
I've done a `git clone https://github.com/ImperialCardioGenetics/UTRannotator.git` into my `./vep/Plugins` directory and have a UTRannotator folder as expected. 

However, I'm getting this error when trying to use `vep -i input.vcf.gz --plugin UTRannotator -o output.vcf.gz`

```
Warning: small ORF file not found. Could use our curated list of uORFs(from sorf.org) at the repository: 'uORF_starts_ends_GRCh37_PUBLIC.txt'
```

And all values for the UTRannotator annotation field are `-`

This is happening for both GRCh37 and GRCh38 input vcfs. Interesting I still get the uORF_starts_ends_GRCh37_PUBLIC.txt error message above when running a GRCh38 vcf

Any help would be great. Thanks!

**Comment by XiaoleiZ** [comment]
Sorry about having the issue. 
It has been tested successfully by us. 
Have you tried our `test.vcf` in the `test` to see whether you can get the same output as `test.output`? 

To remove the warning, you would use the small ORF file with command (for example I am using VEP online database):
`vep -i test.vcf --database --hgvs --tab --port 3337 --force_overwrite -plugin UTRannotator, $HOME/.vep/Plugins/uORF_starts_ends_GRCh37_PUBLIC.txt -o test.output`

**Comment by mvelinder** [comment]
Thanks for the reply. 

I did some debugging with the `test.vcf` file and I think it may be related to the `--tab` or `--fields` options in VEP. Here is the command I ran:

`vep -i test.vcf --fork 40 --cache --dir_cache $cache --dir_plugins $plugins --plugin UTRannotator,/path/to/.vep/Plugins/UTRannotator/uORF_starts_ends_GRCh38_PUBLIC.txt --tab --fields "Location,Allele,SYMBOL,IMPACT,Consequence,Protein_position,Amino_acids,Existing_variation,UTRannotator" --force_overwrite -o test.vcf.vep`

I don't receive the `small ORF file not found` warning anymore. But every value in the UTRannotator column is `-` still. Also within the .vep file output header, UTRannotator is undefined

```
## UTRannotator : ?
```

However, if I run this command, removing the `--tab` and `--fields` and just use the default VEP output format:

`vep -i test.vcf --fork 40 --cache --dir_cache $cache --dir_plugins $plugins --plugin UTRannotator,/path/to/.vep/Plugins/UTRannotator/uORF_starts_ends_GRCh38_PUBLIC.txt --force_overwrite -o test.vcf.out` 

I do receive the UTRannotator annotations in the Extra column

Would it be possible to make the plugin compatible with `--tab` and `--fields` outputs? I assume other VEP users are using these output options as well.

Thanks again!

**Comment by XiaoleiZ** [comment]
There are two issues here:

1. `--fields` is not used with VEP default output. https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_fields

2. I realise the current output format might not be optimised and friendly for VEP default output or VCF output. It is designed for tab-delimited output.  It's an issue I struggle with in developing. As the number of detailed annotations from the plugins varies depending the effect and number of uORFs it affects. Thus I chose to concatenated the outputs as one field. Do you have any suggestion on improving this? Thank you for testing it and pointing it out anyway.

**Comment by XiaoleiZ** [comment]
Hi 

I've updated the output format. Now it works well with VEP default output, tab-delimited output and VCF output now! Have a check.

**Comment by XiaoleiZ** [comment]
The issue has been solved. I am closing it.

**Comment by mvelinder** [comment]
Hmm, I am still getting the same behavior using the following code. 

`vep -i test.vcf --fork 40 --cache --dir_cache $cache --dir_plugins $plugins --plugin UTRannotator,/path/to/uORF_starts_ends_GRCh38_PUBLIC.txt --tab --fields "Location,Allele,SYMBOL,IMPACT,Consequence,UTRannotator" --force_overwrite -o test.vcf.vep`

This is a portion of the `test.vcf.vep` output I'm getting:

```
## Location : Location of variant in standard coordinate format (chr:start or chr:start-end)
## Allele : The variant allele used to calculate the consequence
## SYMBOL : Gene symbol (e.g. HGNC)
## IMPACT : Subjective impact classification of consequence type
## Consequence : Consequence type
## UTRannotator : ?
#Location	Allele	SYMBOL	IMPACT	Consequence	UTRannotator
5:36877039-36877040	A	-	MODIFIER	5_prime_UTR_variant	-
5:36877039-36877040	A	-	MODIFIER	5_prime_UTR_variant	-
5:36877039-36877040	A	-	MODIFIER	upstream_gene_variant	-
5:36877039-36877040	A	-	MODIFIER	upstream_gene_variant	-
5:36877039-36877040	A	-	MODIFIER	upstream_gene_variant	-
5:36877039-36877040	A	-	MODIFIER	5_prime_UTR_variant	-
8:21988220	G	-	MODIFIER	intron_variant	-
8:21988220	G	-	MODIFIER	intron_variant	-
8:21988220	G	-	MODIFIER	upstream_gene_variant	-
8:21988220	G	-	MODIFIER	upstream_gene_variant	-
1:113498814	T	-	MODIFIER	intron_variant	-
1:113498814	T	-	MODIFIER	intron_variant	-
1:113498814	T	-	MODIFIER	intron_variant	-
1:113498814	T	-	MODIFIER	intron_variant	-
1:113498814	T	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
11:31828462-31828463	-	-	MODIFIER	non_coding_transcript_exon_variant	-
4:154125682-154125683	ATGC	-	MODIFIER	intron_variant,non_coding_transcript_variant	-
```

Where you can see all of the UTRannotator column values are still `-`

Could you give me the command you're using that is working with `--tab` and `--fields`?

Thank you!

**Comment by XiaoleiZ** [comment]
Hi, 

The plugin is meant to annotate 5'UTR variants creating or disrupting uORFs. If a 5'UTR variant doesn't have these consequences, it would only output the number of existing uORFs. 

In terms of the output, --tab is not used with output format vcf, please check with VEP documentation.  My command to generate tab-limited txt output can be found here https://github.com/ImperialCardioGenetics/UTRannotator/blob/master/test/run_vep.sh 

Hope it helps.

**Comment by XiaoleiZ** [comment]
Hello, 

This is due to the field name used in the command. 

The output field names from UTRannotator includes: **existing_InFrame_oORFs**, **existing_OutOfFrame_oORFs**, **existing_uORFs**, **five_prime_UTR_variant_annotation**, **five_prime_UTR_variant_consequence**. 

If you want to use fields, you shall include any of the above in the `--fields` argument instead of `UTRannotator`. 

Xiaolei

**Comment by mvelinder** [comment]
Thank you! This working with my changed test command from above:

`vep -i test.vcf --cache --dir_cache /path/to/cache/ --dir_plugins /path/to/plugins --plugin UTRannotator,/path/to/uORF_starts_ends_GRCh37_PUBLIC.txt --tab --force_overwrite --fields "Location,Allele,SYMBOL,IMPACT,Consequence,five_prime_UTR_variant_consequence" -o test_output.txt`

gives:

```
## five_prime_UTR_variant_consequence : Output the variant consequences of a given 5 prime UTR variant: uAUG_gained, uAUG_lost, uSTOP_lost or uFrameshift
#Location	Allele	SYMBOL	IMPACT	Consequence	five_prime_UTR_variant_consequence
5:36877039-36877040	A	-	MODIFIER	5_prime_UTR_variant	uFrameShift
5:36877039-36877040	A	-	MODIFIER	5_prime_UTR_variant	uFrameShift
5:36877039-36877040	A	-	MODIFIER	upstream_gene_variant	-
5:36877039-36877040	A	-	MODIFIER	upstream_gene_variant	-
5:36877039-36877040	A	-	MODIFIER	upstream_gene_variant	-
5:36877039-36877040	A	-	MODIFIER	5_prime_UTR_variant	uFrameShift
```

I will use those specific fields going forward.
